--
-- PostgreSQL database dump
--

-- Dumped from database version 14.7
-- Dumped by pg_dump version 14.7

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


--
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


--
-- Name: update_updated_at_column(); Type: FUNCTION; Schema: public; Owner: root
--

CREATE FUNCTION public.update_updated_at_column() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
        BEGIN
            NEW.updated_at = timezone('Asia/Almaty', NOW());
            RETURN NEW;
        END;
        $$;


ALTER FUNCTION public.update_updated_at_column() OWNER TO root;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cart; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.cart (
    id integer NOT NULL,
    item_id integer,
    item_count integer,
    title character varying(50),
    price numeric(9,2),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    order_status boolean DEFAULT false,
    user_id text
);


ALTER TABLE public.cart OWNER TO root;

--
-- Name: cart_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.cart ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: category_menu; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.category_menu (
    id integer NOT NULL,
    title text,
    photo text,
    "position" smallint DEFAULT 0,
    url text
);


ALTER TABLE public.category_menu OWNER TO root;

--
-- Name: category_menu_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.category_menu ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_menu_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: items_menu; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.items_menu (
    id integer NOT NULL,
    title character varying(50),
    description text,
    photo text,
    price numeric(9,2),
    category_id integer
);


ALTER TABLE public.items_menu OWNER TO root;

--
-- Name: items_menu_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.items_menu ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.items_menu_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders_hall; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.orders_hall (
    id integer NOT NULL,
    admin_id text,
    admin_name text,
    created_at date DEFAULT (timezone('Asia/Almaty'::text, CURRENT_TIMESTAMP))::date NOT NULL,
    updated_at date DEFAULT (timezone('Asia/Almaty'::text, CURRENT_TIMESTAMP))::date NOT NULL,
    last_activity text,
    order_status boolean DEFAULT false,
    table_number smallint,
    admin_answer character varying(12),
    chat_id text,
    user_id text,
    username text,
    full_name text,
    data_reservation date NOT NULL,
    time_reservation character varying(5),
    number_person smallint,
    phone text,
    comment text
);


ALTER TABLE public.orders_hall OWNER TO root;

--
-- Name: orders_hall_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.orders_hall ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_hall_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: personal; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.personal (
    id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    table_number text,
    personal text,
    comment text
);


ALTER TABLE public.personal OWNER TO root;

--
-- Name: personal_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.personal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.personal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: prize; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.prize (
    id integer NOT NULL,
    title text,
    status boolean DEFAULT false
);


ALTER TABLE public.prize OWNER TO root;

--
-- Name: prize_codes; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.prize_codes (
    id integer NOT NULL,
    code bigint DEFAULT (floor((random() * (((999999 - 10) + 1))::double precision)) + (1)::double precision),
    code_description text,
    user_id text,
    code_status boolean DEFAULT true
);


ALTER TABLE public.prize_codes OWNER TO root;

--
-- Name: prize_codes_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.prize_codes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prize_codes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: prize_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.prize ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prize_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: promotions; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.promotions (
    id integer NOT NULL,
    created_at date DEFAULT (timezone('Asia/Almaty'::text, CURRENT_TIMESTAMP))::date NOT NULL,
    updated_at date DEFAULT (timezone('Asia/Almaty'::text, CURRENT_TIMESTAMP))::date NOT NULL,
    url text,
    status boolean DEFAULT false
);


ALTER TABLE public.promotions OWNER TO root;

--
-- Name: promotions_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.promotions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.promotions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: review; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.review (
    id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    text text,
    username text,
    status boolean DEFAULT false,
    admin_id text
);


ALTER TABLE public.review OWNER TO root;

--
-- Name: review_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shipping; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.shipping (
    id integer NOT NULL,
    tpc json,
    number_of_devices integer,
    address text,
    phone text,
    data_reservation date NOT NULL,
    time_reservation character varying(5),
    final_summa numeric(9,2),
    pay_method character varying(16),
    created_at date DEFAULT (timezone('Asia/Almaty'::text, CURRENT_TIMESTAMP))::date NOT NULL,
    updated_at date DEFAULT (timezone('Asia/Almaty'::text, CURRENT_TIMESTAMP))::date NOT NULL,
    order_status boolean DEFAULT true,
    admin_name text,
    admin_id text,
    admin_answer text,
    user_id text,
    user_name text
);


ALTER TABLE public.shipping OWNER TO root;

--
-- Name: shipping_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.shipping ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shipping_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: task; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.task (
    id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    execution_date timestamp without time zone,
    admin_name text,
    type_mailing text,
    picture text,
    message text,
    status text DEFAULT 'draft'::text,
    error text,
    keyboard text
);


ALTER TABLE public.task OWNER TO root;

--
-- Name: task_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.task ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.task_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.users (
    id integer NOT NULL,
    user_id text,
    username text,
    full_name text,
    gender character varying(1),
    age_group text,
    referral text,
    referral_id text DEFAULT gen_random_uuid() NOT NULL,
    card_fio text,
    card_phone text,
    card_number bigint DEFAULT (floor((random() * (((999999 - 10) + 1))::double precision)) + (1)::double precision),
    card_status boolean DEFAULT false,
    birthday date,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    prize integer DEFAULT 0,
    balance integer DEFAULT 0,
    administrator boolean DEFAULT false,
    director boolean DEFAULT false,
    ban_status boolean DEFAULT false,
    reason_for_ban text,
    last_activity text,
    ban_date date
);


ALTER TABLE public.users OWNER TO root;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: cart; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.cart (id, item_id, item_count, title, price, created_at, updated_at, order_status, user_id) FROM stdin;
\.


--
-- Data for Name: category_menu; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.category_menu (id, title, photo, "position", url) FROM stdin;
2	Салаты	\N	2	https://teletype.in/@andreytikhonov/JdFLWQTqYIa1
1	Горячие Закуски	\N	1	https://teletype.in/@andreytikhonov/t5zLmjfYow01
\.


--
-- Data for Name: items_menu; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.items_menu (id, title, description, photo, price, category_id) FROM stdin;
1	Долма с бараниной	Порция: 300г.\n\nНежное мясо барашка, мелко порубленное и приправленное ароматной свежей зеленью со специями, в сочных листьях винограда. Подается закуска с густым домашним мацони. Можно добавить в мацони чеснок.	AgACAgIAAxkBAAJwhGQcSsLYCb4HXwyNaacVi7pzXK2-AAIfzDEbxBrhSEtu3PV1O0pJAQADAgADeAADLwQ	550.00	1
2	Долма со свининой и телятиной	Порция: 300г\n\nФарш из натуральной свинины и говядины, томленный с душистыми пряностями в листьях винограда. Подается закуска со свежим мацони, приготовленным по домашнему рецепту. Можно добавить в мацони чеснок.	AgACAgIAAxkBAAJwiGQcSvTStLFtWKWxHXVMps_3WOALAAIgzDEbxBrhSAABcMdfl56tkAEAAwIAA3gAAy8E	520.00	1
3	Жареная кюрза	Порция: 150г.\n\nУзорчатые пельмени, вылепленные вручную и обжаренные до румяной корочки, с сочной мясной начинкой из рубленой баранины. Подаются с порцией густой сметаны.	AgACAgIAAxkBAAJwjGQcSyon44w8n-v1vtDe5F8oXCOtAAIhzDEbxBrhSFfVOXtwJOScAQADAgADeAADLwQ	430.00	1
4	Теплый салат с телятиной	Порция: 250г.\n\nМягкое мясо теленка, порубленное на кусочки и дополненное сочными солеными огурчиками, сладкими томатами черри, золотистыми дольками миниатюрного картофеля и свежей зеленью салата романо. Завершается блюдо яйцом пашот с жидким, едва схватившимся желтком внутри.	AgACAgIAAxkBAAJwkGQcS3w36BUyW69EHBu9bCEdTJrzAAIizDEbxBrhSBt5bH5sTSkXAQADAgADeAADLwQ	520.00	2
5	Теплый салат с семгой	Порция: 210г.\n\nРумяные ломтики филе семги, золотистые дольки мини-картофеля и сладкие томаты черри, сдобренные пряным сливочно-соевым соусом и присыпанные семечками тыквы, на подушки из зелени свежего салата.	AgACAgIAAxkBAAJwlGQcS8BrcLoHTRLLTbk67N112-FSAAIlzDEbxBrhSHUHsHedKd_HAQADAgADeAADLwQ	690.00	2
6	Цезарь с креветками	Порция: 250г.\n\nХрустящие завитки креветок, сладкие томаты черри и половинки отварных перепелиных яиц, выложенные на подушку из зелени салатных листьев и украшенные румяными гренками из белого хлеба. Заправляется блюдо соусом цезарь с особым пикантно-пряным вкусом.	AgACAgIAAxkBAAJwmGQcS_7qFo9Mf9Hmsty2xZXuqD5lAAImzDEbxBrhSGO4Y_zCm37NAQADAgADeAADLwQ	640.00	2
\.


--
-- Data for Name: orders_hall; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.orders_hall (id, admin_id, admin_name, created_at, updated_at, last_activity, order_status, table_number, admin_answer, chat_id, user_id, username, full_name, data_reservation, time_reservation, number_person, phone, comment) FROM stdin;
\.


--
-- Data for Name: personal; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.personal (id, created_at, table_number, personal, comment) FROM stdin;
\.


--
-- Data for Name: prize; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.prize (id, title, status) FROM stdin;
8	Кальян	f
14	Пицца 4 сыра	t
\.


--
-- Data for Name: prize_codes; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.prize_codes (id, code, code_description, user_id, code_status) FROM stdin;
\.


--
-- Data for Name: promotions; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.promotions (id, created_at, updated_at, url, status) FROM stdin;
\.


--
-- Data for Name: review; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.review (id, created_at, updated_at, text, username, status, admin_id) FROM stdin;
6	2023-03-23 10:38:04.090024+00	2023-03-23 10:38:04.090024	Отличный ресторан, вкусная еда, обслуживание на высшем уровне, особенно понравилось нововведение - Телеграм бот	TikhonovAndrey	t	\N
7	2023-03-23 10:44:06.125178+00	2023-03-23 10:44:06.125178	Очень понравилось нововведение - телеграм бот👍👍👍	Tixontester	t	\N
8	2023-03-24 13:24:34.099545+00	2023-03-24 13:24:34.099545	Внимательный сервис .ОСОБЕННЫЙ ПОДХОД К КЛИЕНТАМ.удобное обращение с этим телег.ботом	Testerbotov1	t	\N
9	2023-03-24 14:28:10.661079+00	2023-03-24 14:28:10.661079	👍👍👍👍	Testerbotov1	t	\N
\.


--
-- Data for Name: shipping; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.shipping (id, tpc, number_of_devices, address, phone, data_reservation, time_reservation, final_summa, pay_method, created_at, updated_at, order_status, admin_name, admin_id, admin_answer, user_id, user_name) FROM stdin;
\.


--
-- Data for Name: task; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.task (id, created_at, updated_at, execution_date, admin_name, type_mailing, picture, message, status, error, keyboard) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.users (id, user_id, username, full_name, gender, age_group, referral, referral_id, card_fio, card_phone, card_number, card_status, birthday, created_at, updated_at, prize, balance, administrator, director, ban_status, reason_for_ban, last_activity, ban_date) FROM stdin;
104	5868624420	Tixontester	Tixon Tester	m	30-40	ce32b414-28b1-422a-a7ca-456f5685c6de	8ad4e303-da83-4ff2-abac-00384b42baa8	Tester Botov	+77770748383	135704	t	1987-03-28	2023-03-24 23:16:09.064431+00	2023-04-04 14:52:35.409286	0	0	f	f	f	-	Доставка клавиатура категорий	\N
77	989322157	Testerbotov1	Alexander	m	30-40	ce32b414-28b1-422a-a7ca-456f5685c6de	18df5ae1-2982-47dd-a711-44008da8451d	Аксёнов Александр	+77052282837	3758	t	1984-07-17	2023-03-24 13:21:41.897422+00	2023-04-04 15:19:20.98717	0	0	f	f	t	😝	О ресторане	2023-04-04
114	553603641	TikhonovAndrey	Tikhonov Andrey	m	30-40	\N	ce32b414-28b1-422a-a7ca-456f5685c6de	Andrey Tikhonov	+77789416399	934578	t	1987-03-30	2023-03-29 13:22:57.316316+00	2023-04-04 15:19:51.763291	4	0	t	f	f	\N	Главное меню	\N
\.


--
-- Name: cart_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.cart_id_seq', 171, true);


--
-- Name: category_menu_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.category_menu_id_seq', 2, true);


--
-- Name: items_menu_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.items_menu_id_seq', 6, true);


--
-- Name: orders_hall_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.orders_hall_id_seq', 40, true);


--
-- Name: personal_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.personal_id_seq', 15, true);


--
-- Name: prize_codes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.prize_codes_id_seq', 30, true);


--
-- Name: prize_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.prize_id_seq', 14, true);


--
-- Name: promotions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.promotions_id_seq', 1, false);


--
-- Name: review_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.review_id_seq', 9, true);


--
-- Name: shipping_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.shipping_id_seq', 35, true);


--
-- Name: task_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.task_id_seq', 77, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.users_id_seq', 132, true);


--
-- Name: cart cart_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.cart
    ADD CONSTRAINT cart_pkey PRIMARY KEY (id);


--
-- Name: category_menu category_menu_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.category_menu
    ADD CONSTRAINT category_menu_pkey PRIMARY KEY (id);


--
-- Name: items_menu items_menu_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.items_menu
    ADD CONSTRAINT items_menu_pkey PRIMARY KEY (id);


--
-- Name: orders_hall orders_hall_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.orders_hall
    ADD CONSTRAINT orders_hall_pkey PRIMARY KEY (id);


--
-- Name: personal personal_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.personal
    ADD CONSTRAINT personal_pkey PRIMARY KEY (id);


--
-- Name: prize_codes prize_codes_code_key; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.prize_codes
    ADD CONSTRAINT prize_codes_code_key UNIQUE (code);


--
-- Name: prize_codes prize_codes_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.prize_codes
    ADD CONSTRAINT prize_codes_pkey PRIMARY KEY (id);


--
-- Name: prize prize_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.prize
    ADD CONSTRAINT prize_pkey PRIMARY KEY (id);


--
-- Name: promotions promotions_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.promotions
    ADD CONSTRAINT promotions_pkey PRIMARY KEY (id);


--
-- Name: review review_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_pkey PRIMARY KEY (id);


--
-- Name: shipping shipping_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.shipping
    ADD CONSTRAINT shipping_pkey PRIMARY KEY (id);


--
-- Name: task task_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.task
    ADD CONSTRAINT task_pkey PRIMARY KEY (id);


--
-- Name: users users_card_number_key; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_card_number_key UNIQUE (card_number);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_referral_id_key; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_referral_id_key UNIQUE (referral_id);


--
-- Name: users users_user_id_key; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_user_id_key UNIQUE (user_id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: cart update_cart_updated_at; Type: TRIGGER; Schema: public; Owner: root
--

CREATE TRIGGER update_cart_updated_at BEFORE UPDATE ON public.cart FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: orders_hall update_orders_hall_updated_at; Type: TRIGGER; Schema: public; Owner: root
--

CREATE TRIGGER update_orders_hall_updated_at BEFORE UPDATE ON public.orders_hall FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: promotions update_promotions_updated_at; Type: TRIGGER; Schema: public; Owner: root
--

CREATE TRIGGER update_promotions_updated_at BEFORE UPDATE ON public.promotions FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: promotions update_review_updated_at; Type: TRIGGER; Schema: public; Owner: root
--

CREATE TRIGGER update_review_updated_at BEFORE UPDATE ON public.promotions FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: task update_review_updated_at; Type: TRIGGER; Schema: public; Owner: root
--

CREATE TRIGGER update_review_updated_at BEFORE UPDATE ON public.task FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: shipping update_shipping_updated_at; Type: TRIGGER; Schema: public; Owner: root
--

CREATE TRIGGER update_shipping_updated_at BEFORE UPDATE ON public.shipping FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: task update_task_updated_at; Type: TRIGGER; Schema: public; Owner: root
--

CREATE TRIGGER update_task_updated_at BEFORE UPDATE ON public.task FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: users update_users_updated_at; Type: TRIGGER; Schema: public; Owner: root
--

CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: items_menu items_menu_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.items_menu
    ADD CONSTRAINT items_menu_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.category_menu(id) ON DELETE CASCADE;


--
-- Name: prize_codes prize_codes_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.prize_codes
    ADD CONSTRAINT prize_codes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- PostgreSQL database dump complete
--

